### PR TITLE
AT 07.01.02 | People > People> Create User

### PR DESCRIPTION
**Pull request by NazLukpan**

### CODE REVIEW

**Review by bahasadyr — APPROVED** [review]

**Review by UmidaKaharova — APPROVED** [review]
Please attach your trello card link

**Comment by NazLukpan** [comment]
https://trello.com/c/uACOTt83/693-at-070102-people-people-create-user

**Comment by NazLukpan** [comment]
https://trello.com/c/uACOTt83

**Comment by NazLukpan** [comment]
https://trello.com/c/uACOTt83/693-at-070102-people-people-create-user

**Pull request merged**
