### PR TITLE
Rf people page test adding allure annotations

### PR DESCRIPTION
**Pull request by ViktoriyaED**

### CODE REVIEW

**Comment by ViktoriyaED** [comment]
[RF | PeoplePageTest > Adding Allure annotations](https://trello.com/c/uOGPE3jb/1415-rf-peoplepagetest-adding-allure-annotations)

**Review by InnaRomankova — APPROVED** [review]
LGTM!

**Review by YuliaMatusevich — APPROVED** [review]

**Review by ServachakM — COMMENTED** [review]
When I refactored my class, I also added the @Step annotation to the methods to avoid returning to that class again. Have @Step annotations already been written?

**Comment by ViktoriyaED** [comment]
> When I refactored my class, I also added the @step annotation to the methods to avoid returning to that class again. Have @step annotations already been written?

I didn't add any @Step annotations because they were already present in the code. :)

**Pull request merged**
