### PR TITLE
ERR | PipelineTest > testEditPipelineDescription

### PR DESCRIPTION
**Pull request by cyferkiBY**
ERR | PipelineTest > testEditPipelineDescription (Trello has 3 ERR-cards with this problem).

- Add ignore [ERR | FolderTest > testDeleteFreestyleProjectInFolder](https://trello.com/c/pXGXXfi6/1094-err-foldertest-testdeletefreestyleprojectinfolder)
- Add waits/scrolls and refactor for stabilizing flaky-tests `testEditPipelineDescription()` and `testWarningMessageIsDisappeared()` in class PipelineTest.

### CODE REVIEW

**Comment by cyferkiBY** [comment]
[ERR | PipelineTest > testEditPipelineDescription](https://trello.com/c/NjPsdXnX/1057-err-pipelinetest-testeditpipelinedescription)

**Comment by cyferkiBY** [comment]
[ERR | PiplineTest > testEditPipelineDescription](https://trello.com/c/Py60pCQj/1046-err-piplinetest-testeditpipelinedescription)

**Comment by cyferkiBY** [comment]
[ERR | PipelineTest > testCreateNewPipelineFromExisting](https://trello.com/c/7KA5fYhI/1047-err-pipelinetest-testcreatenewpipelinefromexisting)

**Comment by cyferkiBY** [comment]
[ERR | NewItemCreatePipelineTest> testWarningMessageIsDisappeared](https://trello.com/c/CspTREa1/915-err-newitemcreatepipelinetest-testwarningmessageisdisappeared)

**Review by IriSamo — APPROVED** [review]

**Review by InnaRomankova — APPROVED** [review]

**Pull request merged**
