### PR TITLE
RF | Structure > Composition of components Header, Footer, Breadcrumbs

### PR DESCRIPTION
**Pull request by cyferkiBY**
**_Don't merge without approval @SergeiDemyanenko or @kartavenkopavel  ._**

**The key changes in class `BasePage.java`.** 

RF | Structure > Composition of components Header, Footer, Breadcrumbs.
- addition of fields `HeaderComponent`, `FooterComponent`, `BredcrumbsComponent ` in the class `BasePage` and getters for them; 
- addition of `HeaderComponent`, `FooterComponent`, `BredcrumbsComponent` into the constructor of the class `BasePage`;
- change classes `HeaderComponent`, `FooterComponent`, `BredcrumbsComponent` to not abstract.
- change inheritances in Page-classes from  `HeaderComponent`, `FooterComponent`, `BredcrumbsComponent` to `BasePage`.
- change tests that used  `HeaderComponent`, `FooterComponent`, `BredcrumbsComponent`.

RF | HeaderTest > testLogoHeadIconIsVisible
- Renaming of the testLogoHeadIconIsSeen to the testLogoHeadIconIsVisible

RF | FooterComponentTest > testFooterLinkJenkinsIsClickable
- Deletion of methods in class ManageJenkinsPage: moveForClinkOnLink
- Refactoring of the method in FooterComponent: clickJenkinsVersion

### CODE REVIEW

**Comment by cyferkiBY** [comment]
[RF | Structure > Composition of components Header, Footer, Breadcrumbs](https://trello.com/c/kEtAGaxX/1144-rf-structure-composition-of-components-header-footer-breadcrumbs)

**Comment by cyferkiBY** [comment]
[RF | FooterComponentTest > testFooterLinkJenkinsIsClickable](https://trello.com/c/CLOUgz88/1147-rf-footercomponenttest-testfooterlinkjenkinsisclickable)

**Comment by cyferkiBY** [comment]
[RF | HeaderTest > testLogoHeadIconIsVisible](https://trello.com/c/SBLuaQbd/1146-rf-headertest-testlogoheadiconisvisible)

**Review by IriSamo — APPROVED** [review]

**Review by RadasIvan — APPROVED** [review]

**Review by kartavenkopavel — CHANGES_REQUESTED** [review]
до субботы закрою

**Pull request closed without merging**
