### PR TITLE
AT 04.10.03 | Folder > Create Pipeline in folder with description

### PR DESCRIPTION
**Pull request by Iriskus**
test createFolderWithDescriptionAndJobPipeline added

### CODE REVIEW

**Comment by Iriskus** [comment]
AT [ ] https://trello.com/c/XzWE0Upu/742-at-041003-folder-create-pipeline-in-folder-with-description

**Comment by snysmymric** [comment]
[AT 04.10.03 | Folder > Create Pipeline in folder with description](https://trello.com/c/XzWE0Upu/742-at-041003-folder-create-pipeline-in-folder-with-description)

**Comment by snysmymric** [comment]
[AT 04.10.03 | Folder > Create Pipeline in folder with description](https://trello.com/c/XzWE0Upu/742-at-041003-folder-create-pipeline-in-folder-with-description)

**Review by snysmymric — APPROVED** [review]
OK

**Review by DenSebrovsky — APPROVED** [review]
LGTM

**Pull request merged**
