### PR TITLE
AT 00.06.10 | New item > Organization folder > User can change status folder to disable

### PR DESCRIPTION
**Pull request by asyniagina**
https://trello.com/c/k9ikibaD/1313-at-000610-new-item-organization-folder-user-can-change-status-folder-to-disable

Added test:

testChangeStatusToDisableOrgFolder()

‌

Added methods:

clickDisableButton();

getWarningTextAboutDisabledOrgFolder();

### CODE REVIEW

**Comment by asyniagina** [comment]
[AT 00.06.10 | New item > Organization folder > User can change status folder to disable](https://trello.com/c/k9ikibaD/1313-at-000610-new-item-organization-folder-user-can-change-status-folder-to-disable)

**Review by InnaRomankova — APPROVED** [review]

**Comment by cyferkiBY** [comment]
LGFM

**Review by cyferkiBY — APPROVED** [review]
LGFM

**Comment by cyferkiBY** [comment]
Всё хорошо, только, пожалуйста, назови PR также как названа карточка в Trello: `AT 00.06.10 | New item > Organization folder > User can change status folder to disable`

**Comment by ServachakM** [comment]
[AT 09.01.01 | Manage Jenkins > Configure system > Change Default view](https://trello.com/c/jW6LAY1U/1317-at-090101-manage-jenkins-configure-system-change-default-view)

**Pull request merged**
