### PR TITLE
TC 04.04.01 | Folder > Delete Folder

### PR DESCRIPTION
**Pull request by kirin608**

### CODE REVIEW

**Comment by kirin608** [comment]
[TC 04.04.01 | Folder > Delete Folder](https://trello.com/c/Pxtu2m1s/616-tc-040401-folder-delete-folder)

**Comment by kirin608** [comment]
[AT 04.04.01 | Folder > Delete Folder](https://trello.com/c/eEOqE5Sv/651-at-040401-folder-delete-folder)

**Review by dmswlpk — APPROVED** [review]

**Review by dmswlpk — APPROVED** [review]

**Review by dmswlpk — APPROVED** [review]

**Comment by kirin608** [comment]
[AT 04.01.01 | Folder > Create Folder in folder](https://trello.com/c/n85IkjqN/449-at-040101-folder-create-folder-in-folder)

**Comment by kirin608** [comment]
[AT 04.02.01 | Folder> Configure folder display name](https://trello.com/c/mfSkwPBv/654-at-040201-folder-configure-folder-display-name)

**Comment by kirin608** [comment]
[AT 04.03.01 | Folder > Add folder description](https://trello.com/c/bB7IJ0K0/653-at-040301-folder-add-folder-description)

**Comment by kirin608** [comment]
[AT 04.04.01 | Folder > Delete Folder](https://trello.com/c/eEOqE5Sv/651-at-040401-folder-delete-folder)

**Pull request merged**
