### PR TITLE
AT 00.05.04| New Item > Multibranch Pipeline | Create new mb pipeline with unsafe characters in the name

### PR DESCRIPTION
**Pull request by judmi**

### CODE REVIEW

**Comment by judmi** [comment]
[AT 00.05.03 | New Item > Multibranch Pipeline | Create new mb pipeline with already existing name](https://trello.com/c/qTHH7nnB/230-at-000503-new-item-multibranch-pipeline-create-new-mb-pipeline-with-already-existing-name)

**Comment by judmi** [comment]
[AT 00.05.04| New Item > Multibranch Pipeline | Create new mb pipeline with unsafe characters in the name](https://trello.com/c/0ZH5LCDu/229-at-000504-new-item-multibranch-pipeline-create-new-mb-pipeline-with-unsafe-characters-in-the-name)

**Comment by judmi** [comment]
[RF | MultibranchPipelineTest > testCreateMbPipelineEmptyName](https://trello.com/c/rGpnCPva/169-rf-multibranchpipelinetest-testcreatembpipelineemptyname)

**Comment by snysmymric** [comment]
Один PR - одно действие. То есть либо тест либо рефакторинг.

**Review by LLrvk — APPROVED** [review]

**Pull request merged**
