### PR TITLE
AT 00.01.02 | New item > Freestyle Project> Create Freestyle Project Using Invalid Name

### PR DESCRIPTION
**Pull request by kristi-w**

### CODE REVIEW

**Comment by kristi-w** [comment]
[AT 00.01.02 | New item > Freestyle Project> Create Freestyle Project Using Invalid Name](https://trello.com/c/niuHpfG9/420-at-000102-new-item-freestyle-project-create-freestyle-project-using-invalid-name)

**Review by veronmolosh — APPROVED** [review]
Please, add space before Assert.

**Comment by kristi-w** [comment]
> I added space before the Assert.

**Review by veronmolosh — APPROVED** [review]
LGTM!

**Review by BabintsevaS — APPROVED** [review]

**Pull request merged**
