### PR TITLE
AT 09.07.01 | Manage Jenkins > Global Tool Configuration > Add Maven name field. Checking the disappearance of the warning message

### PR DESCRIPTION
**Pull request by patriotby07**
https://trello.com/c/WC52Tasd/630-at-090701-manage-jenkins-global-tool-configuration-add-maven-name-field-checking-the-disappearance-of-the-warning-message

### CODE REVIEW

**Comment by patriotby07** [comment]
[AT 09.07.01 | Manage Jenkins > Global Tool Configuration > Add Maven name field. Checking the disappearance of the warning message](https://trello.com/c/WC52Tasd/630-at-090701-manage-jenkins-global-tool-configuration-add-maven-name-field-checking-the-disappearance-of-the-warning-message)

**Review by cyferkiBY — APPROVED** [review]
LGFM

**Review by olpolezhaeva — APPROVED** [review]

**Comment by YuliaMatusevich** [comment]
[AT 09.08.01 | Manage Jenkins > Global Tool Configuration > Add Maven name field. Checking the disappearance of the warning message](https://trello.com/c/WC52Tasd/630-at-090801-manage-jenkins-global-tool-configuration-add-maven-name-field-checking-the-disappearance-of-the-warning-message)

**Comment by YuliaMatusevich** [comment]
[AT 09.08.01 | Manage Jenkins > Global Tool Configuration > Add Maven name field. Checking the disappearance of the warning message](https://trello.com/c/WC52Tasd/630-at-090801-manage-jenkins-global-tool-configuration-add-maven-name-field-checking-the-disappearance-of-the-warning-message)

**Comment by YuliaMatusevich** [comment]
[AT 09.08.01 | Manage Jenkins > Global Tool Configuration > Add Maven name field. Checking the disappearance of the warning message](https://trello.com/c/WC52Tasd/630-at-090801-manage-jenkins-global-tool-configuration-add-maven-name-field-checking-the-disappearance-of-the-warning-message)

**Pull request merged**
