### PR TITLE
RF_PeoplePageTest

### PR DESCRIPTION
**Pull request by LiudmilaPlucci**
RF people page test
Rename fork with unsafe symbol

### CODE REVIEW

**Comment by LiudmilaPlucci** [comment]
[RF | PeoplePageTest](https://trello.com/c/L7BaR0hF/1086-rf-peoplepagetest)

**Comment by LiudmilaPlucci** [comment]
[RF | PeoplePageTest](https://trello.com/c/L7BaR0hF/1086-rf-peoplepagetest)

**Comment by LiudmilaPlucci** [comment]
[RF | PeoplePageTest](https://trello.com/c/L7BaR0hF/1086-rf-peoplepagetest)

**Review by starnetsd — APPROVED** [review]

**Review by cyferkiBY — APPROVED** [review]
LGFM

**Pull request merged**
