### PR TITLE
ERR|OrganizationFolderTest>testDeleteOrganizationFolder and ERR|OrganizationFolderTest>testMoveOrgFolderToFolder

### PR DESCRIPTION
**Pull request by cyferkiBY**
[ERR | OrganizationFolderTest > testDeleteOrganizationFolder](https://trello.com/c/hIAnaOSa/467-err-organizationfoldertest-testdeleteorganizationfolder)
and 
[ERR|OrganizationFolderTest>testMoveOrgFolderToFolder](https://trello.com/c/byBdt8Te/503-err-organizationfoldertest-testmoveorgfoldertofolder)

### CODE REVIEW

**Comment by cyferkiBY** [comment]
[ERR | OrganizationFolderTest > testDeleteOrganizationFolder](https://trello.com/c/hIAnaOSa/467-err-organizationfoldertest-testdeleteorganizationfolder)

**Comment by cyferkiBY** [comment]
[ERR | OrganizationFolderTest > testMoveOrgFolderToFolder](https://trello.com/c/byBdt8Te/503-err-organizationfoldertest-testmoveorgfoldertofolder)

**Comment by cyferkiBY** [comment]
[ERR | OrganizationFolderTest > testMoveOrgFolderToFolder](https://trello.com/c/byBdt8Te/503-err-organizationfoldertest-testmoveorgfoldertofolder)

**Review by InaChemerko — APPROVED** [review]
Approve

**Review by yuriiormson — APPROVED** [review]

**Review by DimaZadrutsiy — APPROVED** [review]

**Pull request merged**
