### PR TITLE
ERR | HeaderTest

### PR DESCRIPTION
**Pull request by VadimTref**
Remove Ignore from 5 tests;
Change locator in method openUserDropdownMenu() 
Add waiters and change locators in 5 tests:
testCountAndNamesItemsInUserDropdownMenu, testUserDropdownMenuToOpenPageAdminBuilds, testUserDropdownMenuToOpenPageAdminConfigure, testUserDropdownMenuToOpenPageAdminMyViews, testUserDropdownMenuToOpenPageAdminCredentials;

### CODE REVIEW

**Comment by VadimTref** [comment]
[ERR | HeaderTest](https://trello.com/c/hziO226d/823-err-headertest)

**Comment by VadimTref** [comment]
[ERR | HeaderTest > test_Logo_HeadIcon_ReloadMainPage](https://trello.com/c/OYMFWWEm/904-err-headertest-testlogoheadiconreloadmainpage)

**Comment by VadimTref** [comment]
[ERR Trello](https://trello.com/c/hziO226d/823-err-headertest)

**Review by EkaterinaTurgunova — APPROVED** [review]

**Comment by UmidaKaharova** [comment]
Мне кажется, некоторые аасерты лучше было оставить на одной строке(не такие длинные)

**Review by UmidaKaharova — APPROVED** [review]

**Pull request merged**
