### PR TITLE
AT 00.02.01 | New item > Create Pipeline | Valid name and save default configure

### PR DESCRIPTION
**Pull request by KamaYilmaz**
https://trello.com/c/8crQrsZ4/433-at-000201-new-item-create-pipeline-valid-name-and-save-default-configure

### CODE REVIEW

**Comment by KamaYilmaz** [comment]
[AT 00.02.01 | New item > Create Pipeline | Valid name and save default configure](https://trello.com/c/8crQrsZ4/433-at-000201-new-item-create-pipeline-valid-name-and-save-default-configure)

**Review by cyferkiBY — APPROVED** [review]
Good!

**Review by dmcalifornia — APPROVED** [review]
Looks good to me. The PR name should be identical to the name of AT card.

**Review by SergeiDemyanenko — CHANGES_REQUESTED** [review]
Ссылка на задачу?

**Comment by KamaYilmaz** [comment]
> Ссылка на задачу?

Spasibo. Dobavila.

**Comment by KamaYilmaz** [comment]
[AT 00.02.01 | New item > Create Pipeline | Valid name and save default configure](https://trello.com/c/8crQrsZ4/433-at-000201-new-item-create-pipeline-valid-name-and-save-default-configure)

**Pull request closed without merging**
